// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prince.Data;

#nullable disable

namespace Prince.Data.Migrations
{
    [DbContext(typeof(PrinceDbContext))]
    [Migration("20260817203508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prince.Domain.Models.Payments.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_paid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("platform_fee");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_id");

                    b.Property<decimal>("ProducerNetAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("producer_net_amount");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("ix_transactions_offer_id");

                    b.HasIndex("ProducerId")
                        .HasDatabaseName("ix_transactions_producer_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Prince.Domain.Models.Payments.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gateway");

                    b.Property<decimal>("GatewayFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("gateway_fee");

                    b.Property<decimal>("NetAmountPaidOut")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("net_amount_paid_out");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_id");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("requested_amount");

                    b.HasKey("Id")
                        .HasName("pk_withdrawals");

                    b.HasIndex("ProducerId")
                        .HasDatabaseName("ix_withdrawals_producer_id");

                    b.ToTable("withdrawals", (string)null);
                });

            modelBuilder.Entity("Prince.Domain.Models.Producers.Producer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_producers");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_producers_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_producers_email");

                    b.ToTable("producers", (string)null);
                });

            modelBuilder.Entity("Prince.Domain.Models.Products.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("RealPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("real_price");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_offers_product_id");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Prince.Domain.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_id");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ProducerId")
                        .HasDatabaseName("ix_products_producer_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Prince.Domain.Models.Payments.Transaction", b =>
                {
                    b.OwnsOne("Prince.Domain.Models.Payments.Buyer", "Buyer", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("buyer_cpf");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("buyer_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("buyer_name");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Buyer")
                        .IsRequired();
                });

            modelBuilder.Entity("Prince.Domain.Models.Producers.Producer", b =>
                {
                    b.OwnsOne("Prince.Domain.Models.Producers.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ProducerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.HasKey("ProducerId");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("ProducerId")
                                .HasConstraintName("fk_producers_producers_id");
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
